name: Rust

on:
  push:
    branches: [ "master", "ci" ]
  pull_request:
    branches: [ "master", "ci" ]

env:
  CARGO_TERM_COLOR: always
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -Cinstrument-coverage
  LLVM_PROFILE_FILE: cargo-test-%p-%m.profraw
  GRCOV: "./grcov/target/release/grcov"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.2.0
    - name: Build Tasks
      run: cargo build --package xtask --verbose
    - name: Build Library
      run: cargo build --package succinct_neo --verbose
    - name: Run tests
      run: cargo xtask test_instr
    - name: Install grcov
      run: |
        rustup component add llvm-tools-preview
        git clone https://github.com/mozilla/grcov
        cargo build --manifest-path grcov/Cargo.toml --release
    - name: Generate Coverage
      run: cargo xtask cover_only lcov
    - name: Cleanup
      run: cargo xtask clean
    - name: Send coverage to Codecov
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x ./codecov
        ./codecov

