name: Rust

on:
  push:
    branches: [ "master", "ci" , "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

env:
  CARGO_TERM_COLOR: always
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -Cinstrument-coverage
  LLVM_PROFILE_FILE: cargo-test-%p-%m.profraw
  GRCOV: "./grcov"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install LLVM Tools
      run: rustup component add llvm-tools-preview
    - name: Download grcov Release
      uses: robinraju/release-downloader@v1.7
      with:
        latest: true
        repository: "mozilla/grcov" 
        fileName: "grcov-x86_64-unknown-linux-gnu.tar.bz2"
    - name: Unzip grcov
      run: "tar -xf grcov-x86_64-unknown-linux-gnu.tar.bz2"
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.2.0
    - name: Build Tasks
      run: cargo build --package xtask --verbose
    - name: Build Library
      run: cargo build --package succinct_neo --verbose
    - name: Run tests
      run: cargo xtask test_instr
    - name: Generate Coverage
      run: cargo xtask cover_only lcov
    - name: Cleanup
      run: cargo xtask clean
    - name: Send coverage to Codecov
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x ./codecov
        ./codecov

